apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.name }}"
data:
  envoy.yaml: |-
    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address: { address: 127.0.0.1, port_value: 9901 }

    static_resources:
      listeners:
      - name: external_service
        address:
          socket_address: { address: 0.0.0.0, port_value: {{ .Values.exposedPort }} }
        filter_chains:
        - filters:
          - name: envoy.filters.network.tcp_proxy
            config:
              stat_prefix: ingress_tcp
              cluster: external_service
              idle_timeout: 600s

      clusters:
      - name: external_service
        connect_timeout: 5s
        type: LOGICAL_DNS
        dns_lookup_family: V4_ONLY
        lb_policy: ROUND_ROBIN
        load_assignment:
          cluster_name: external_service
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: {{ .Values.host }}
                    port_value: {{ .Values.port }}
        {{ if .Values.tlsEnabled -}}
        transport_socket:
          name: envoy.transport_sockets.tls
        {{- end }}
