apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    app: "{{ .Values.name }}"
  type: NodePort
  ports:
  - port: {{ .Values.exposedPort }}
    name: service
    protocol: TCP
